spring:
  cloud:
    stream:
      bindings:
        output:
          destination: transformed
          #binder: local_rabbit
          binder: local_kafka
          consumer:
            max-attempts: 3
            # retry-template-name: whatever
        test-sink:
          destination: transformed
          #binder: local_rabbit
          binder: local_kafka
        input:
          destination: testtock
          #binder: local_rabbit
          binder: local_kafka
        test-source:
          destination: testtock
          #binder: local_rabbit
          binder: local_kafka
      binders:
        local_kafka:
          type: kafka
#        local_rabbit:
#          type: rabbit
      rabbit:
        bindings:
          local_rabbit:
            consumer:
              max-length: 100
              prefetch: 1
              requeue-rejected: true
              republish-to-dlq: true
              auto-bind-dlq: true
            producer:
              # max-length: 100
              batching-enabled: false
              batch-size: 100
              transacted: true
              auto-bind-dlq: true
